"""Export the Python app's catalogue, CFA notes and company datasets to a JS module.

The web version (artifact) and the Streamlit app share one source of truth:
datasets/companies/* and lab/metrics.py, lab/cfa.py, lab/valuation.py.

    python3 scripts/export_data.py   ->  src/generated/data.js
"""

from __future__ import annotations

import json
import math
import sys
from dataclasses import asdict
from pathlib import Path

WEB = Path(__file__).resolve().parent.parent
APP = WEB.parent
sys.path.insert(0, str(APP))

from lab import cfa, data, metrics, ratios, valuation  # noqa: E402


def clean(x):
    if isinstance(x, float) and (math.isnan(x) or math.isinf(x)):
        return None
    return x


def main() -> None:
    metric_rows = []
    for m in metrics.CATALOG.values():
        d = asdict(m)
        d["sectors"] = list(m.sectors)
        d["plausible"] = list(m.plausible)
        d["hard"] = list(m.hard)
        metric_rows.append(d)

    companies = []
    for p in data.list_companies():
        values, meta = data.load_starter(p["id"])
        rows = {}
        for key in values.index:
            rows[key] = {str(y): clean(float(values.at[key, y])) for y in values.columns}
        companies.append(
            {
                "profile": p,
                "years": [int(y) for y in values.columns],
                "values": rows,
                "meta": {k: {"source": meta.at[k, "source"], "note": meta.at[k, "note"]} for k in meta.index},
            }
        )

    ratio_rows = []
    for r in ratios.RATIOS.values():
        ratio_rows.append({
            "key": r.key, "en": r.en, "de": r.de, "text": r.text, "unit": r.unit, "sectors": list(r.sectors),
            "higher_is_better": r.higher_is_better, "core": r.core, "cfa": r.cfa,
            "inputs": [{"metric": i.metric, "averaged": i.averaged, "opening": (r.key, i.metric) in ratios.OPENING_BALANCE} for i in r.inputs],
            "interpretation": r.interpretation, "benchmark": r.benchmark,
        })

    out = {
        "RATIOS": ratio_rows,
        "METRICS": metric_rows,
        "ALIASES": metrics.ALIASES,
        "DEFAULT_YEARS": metrics.DEFAULT_YEARS,
        "CFA": {k: list(v) for k, v in cfa.CFA.items()},
        "METHOD_GUIDE": [asdict(g) for g in valuation.METHOD_GUIDE],
        "COMPANIES": companies,
    }
    target = WEB / "src" / "generated"
    target.mkdir(parents=True, exist_ok=True)
    js = "// Generated by scripts/export_data.py from the Python app — do not edit by hand.\n"
    for k, v in out.items():
        js += f"export const {k} = {json.dumps(v, ensure_ascii=False, indent=1)};\n"
    (target / "data.js").write_text(js, encoding="utf-8")
    print(f"wrote {target / 'data.js'} ({len(js) // 1024} KB, {len(companies)} companies, {len(metric_rows)} metrics)")


if __name__ == "__main__":
    main()
